sudo: false

language: php

php:
  - '8.2.13'
  - '8.3.2'

before_script:
  - composer config -g http-basic.repo.packagist.com token $PACKAGIST_AUTHENTICATION_TOKEN
  - if [ ! -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then
    composer global require olivertappin/phpcs-diff;
    sudo ln -s ~/.config/composer/vendor/bin/phpcs-diff /usr/bin/phpcs-diff;
    git fetch `git remote get-url origin` $TRAVIS_BRANCH\:refs/remotes/origin/$TRAVIS_BRANCH;
    fi;
  - php -dmemory_limit=-1 $HOME/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/composer install --no-interaction
  - export APP_ENV="local"

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "${TRAVIS_PHP_VERSION}" == "8.2" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
