sudo: false

language: php

php:
  - '8.2.13'
  - '8.3.2'

before_script:
  - composer update --prefer-dist ${COMPOSER_ARGUMENTS}

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "${TRAVIS_PHP_VERSION}" == "8.2" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
